# Generated by Django 6.1 on 2026-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PF_App', '0004_faq_delete_faqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('date_range', models.CharField(help_text='e.g. January 2025 – May 2025 · Delhi, India', max_length=100)),
                ('is_fulltime', models.BooleanField(default=False)),
                ('bullets', models.TextField(help_text='One bullet point per line')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('wip', 'In progress'), ('archived', 'Archived')], default='wip', max_length=20)),
                ('icon', models.CharField(default='💻', help_text='Emoji icon', max_length=10)),
                ('live_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('tags', models.CharField(default='', help_text='Comma-separated tags, e.g. Django,Python,SQLite3', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Vipul Kumar', max_length=100)),
                ('first_name', models.CharField(default='Vipul', max_length=50)),
                ('last_name', models.CharField(default='Kumar', max_length=50)),
                ('tagline', models.CharField(default='BCA student, Django developer, and lifelong builder.', max_length=200)),
                ('hero_description', models.TextField(default='I build clean, fast, and scalable web applications.')),
                ('about_bio_1', models.TextField(blank=True, default='')),
                ('about_bio_2', models.TextField(blank=True, default='')),
                ('about_bio_3', models.TextField(blank=True, default='')),
                ('location', models.CharField(default='Delhi, India', max_length=100)),
                ('education', models.CharField(default='BCA · BCIT 2022–25', max_length=150)),
                ('email', models.EmailField(default='vipulsam1234@gmail.com', max_length=254)),
                ('github_url', models.URLField(default='https://github.com/Vipul-Kumar-Dev')),
                ('github_handle', models.CharField(default='Vipul-Kumar-Dev', max_length=100)),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/vipul-kumar-dev/')),
                ('linkedin_handle', models.CharField(default='vipul-kumar-dev', max_length=100)),
                ('languages', models.CharField(default='English, Hindi', max_length=100)),
                ('resume_note', models.CharField(default='Get the full picture — all my experience, skills, and projects in one clean PDF.', max_length=200)),
                ('footer_copy', models.CharField(default='© 2025 Vipul Kumar · Built with Django', max_length=200)),
                ('stat_projects', models.CharField(default='3+', max_length=20)),
                ('stat_internships', models.CharField(default='2', max_length=20)),
                ('stat_technologies', models.CharField(default='8+', max_length=20)),
                ('stat_experience', models.CharField(default='1.5y', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('percentage', models.PositiveSmallIntegerField(default=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TypedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
